### PR TITLE
Fix IG dependsOn.reason conversion

### PR DESCRIPTION
**Pull request by lmckenzi**

### CODE REVIEW

**Comment by lmckenzi** [comment]
This addresses https://github.com/HL7/fhir-ig-publisher/issues/655

**Comment by lmckenzi** [comment]
Separated out changes from 1813 (re-submitted as https://github.com/hapifhir/org.hl7.fhir.core/pull/1818)

**Review by grahamegrieve — COMMENTED** [review]
you only fixed one of the two?

**Comment by lmckenzi** [comment]
Sigh.  Because I was a twit.  Fixed

**Review by grahamegrieve — APPROVED** [review]
ok

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
