### PR TITLE
update projects to hapi-fhir-base 3.8.0-snapshot

### PR DESCRIPTION
**Pull request by oliveregger**
the hapi project is currently on version 3.8.0-SNAPSHOT,  org.hl7.fhir.core.[dstu2, dstu201, dstu3, r4, r5] have a dependency to hap-fhir-base 3.7.0-SNAPSHOT. Changed the dependency of the this core projects with the pull request to hapi-fhir-base 3.8.0-SNAPSHOT.

Is a GForge ticket need for that pull request?

BTW: Should org.hl7.fhir.core really depend on hapi-fhir-base? Would it make sense to extract the interfaces from hapi-fhir-base to org.hl7.fhir.core?

### CODE REVIEW

**Comment by jamesagnew** [comment]
Hi @oliveregger !

FYI- I have a set of branches that I'll be landing in the next day or two that overlap with this. It's a bit complicated to land because I need to simultaneously update HAPI FHIR, org.hl7.fhir.core, and hl7-fhir but I have this all basically done.

Will revisit this PR after that.

**Comment by oliveregger** [comment]
Hi @jamesagnew great that you are working on that! I don't think there will be anything needed from this PR, too bad I did not see the branches before. I have it that far at the moment, that I can use hapi-fhir with the mavenized core r4 structures, see https://github.com/jamesagnew/hapi-fhir/compare/master...ahdis:oliveregger_fhircore if interested.

**Comment by grahamegrieve** [comment]
@jamesagnew should we close this then?

**Comment by oliveregger** [comment]
org.hl7.fhir.core.[dstu2, dstu201, dstu3, r4, r5] still have a dependency to hap-fhir-base 3.7.0-SNAPSHOT
on master:

[INFO] --- maven-dependency-plugin:3.0.2:tree (default-cli) @ org.hl7.fhir.r5 ---
[INFO] ca.uhn.hapi.fhir:org.hl7.fhir.r5:jar:3.7.33-SNAPSHOT
[INFO] +- ca.uhn.hapi.fhir:org.hl7.fhir.utilities:jar:3.7.33-SNAPSHOT:compile
[INFO] +- ca.uhn.hapi.fhir:hapi-fhir-base:jar:3.7.0-SNAPSHOT:compile

**Comment by jamesagnew** [comment]
FYI- I'm not actually abandoning this PR.

I am intending to merge and reconcile once HAPI FHIR 3.8.0 is released on May 23.

**Comment by oliveregger** [comment]
obsolete with development to 4.0.0

**Pull request closed without merging**
