### PR TITLE
FML transform performance tuning

### PR DESCRIPTION
**Pull request by mrunibe**
Imrove performance of FML transform, especially for data with large lists.

- Skip numberChildren() when adding an element to a list: https://github.com/hapifhir/org.hl7.fhir.core/issues/1699
- Avoid creating new FHIRPathEngine in every new Property: https://github.com/hapifhir/org.hl7.fhir.core/issues/1703

For large amount of input/output data, FML transform is > 1000x faster and using less memory.

### CODE REVIEW

**Comment by grahamegrieve** [comment]
why is it ok to skip numberChildren() when changing the list?

**Comment by mrunibe** [comment]
> why is it ok to skip numberChildren() when changing the list?

At least **during** the transform I have not seen where the index is used. But maybe we can just defer numberChildren() until the end of the transform? For example, do it when sorting: https://github.com/hapifhir/org.hl7.fhir.core/blob/1ad319ee35f63f7163c336261fcf296293e69dc4/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/utils/structuremap/StructureMapUtilities.java#L1274-L1277

I've also noticed the numbering is not done in other place like [forceElement](https://github.com/hapifhir/org.hl7.fhir.core/blob/1ad319ee35f63f7163c336261fcf296293e69dc4/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/elementmodel/Element.java#L591) or [addElement](https://github.com/hapifhir/org.hl7.fhir.core/blob/1ad319ee35f63f7163c336261fcf296293e69dc4/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/elementmodel/Element.java#L1364), making me naively assume it might not be required in makeElement either.

Do you think defering it to the end of transform() is ok?

**Comment by oliveregger** [comment]
@mrunibe thanks for that performance optimisation, this has a huge speed impact!

I had a look at the issue with numberChildren(), I think one cause of the performance issue numberChildren is that numberChildren is called recursively within the children, 

https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/elementmodel/Element.java#L291
			child.numberChildren();

if @grahamegrieve aggres, maybe you could update your PR and adapt that numberChildren() is not calling child.nubmerChildren?

i tested the approach with matchbox for the upcoming next version and all transformation and validation tests are passing with that approach, looks really promising.

**Comment by grahamegrieve** [comment]
The point of numberChildren is that it calls recursively. @dotasek and I reviewed this, and I have to investigate when it is and isn't safe to not call numberChildren

**Comment by oliveregger** [comment]
> The point of numberChildren is that it calls recursively. 

why would that be necessary? if a child is inserted and that child would have itself a list of elements, should there the indexes not already be populated?

>@dotasek and I reviewed this, and I have to investigate when it is and isn't safe to not call numberChildren

thanks!

An alternative would be maybe to handle the indexes directly in NamedItem and sync the index there during manipulation add/remove? if you think that would be an option i could work on a pr for that.

**Comment by mrunibe** [comment]
Following up on the idea from @oliveregger handling the indices directly:
 
NamedItemList already contains a per list map that we can use to get the current size and therefore set the index immediately when adding a child. This should be equivalent to calling numberChildren.

I changed this accordingly (https://github.com/hapifhir/org.hl7.fhir.core/pull/1704/commits/8d780e078492cc310603f71bc47e8326fef8740e) and also added a check in the testcases (https://github.com/hapifhir/org.hl7.fhir.core/pull/1704/commits/f909a0c228d84ab5232e3f335c9eab4dfb6121d8)

**Review by grahamegrieve — APPROVED** [review]
ok - thanks

**Pull request merged**
