### PR TITLE
Adding support for date/Quantity arithmetic to FHIRPathEngine

### PR DESCRIPTION
**Pull request by keithboone**
There are a number of deficiencies in the FHIRPathEngine that we detected during Connectathon 25 in the SANER Track.  This is the first of the changes addressing these issues, correcting the issue that date +/- Quantity is at yet unsupported in FHIRPathEngine.

This package of changes includes the following:
1. Modification of FHIRPathEngine exception to support setting and retrieving the text and location of an error in the expression being evaluated.
2. Modifications to FHIRPathEngine.execute() to report error location during execution
3. Addition of date +/- Quantity test cases (both positive and negative).
4. Addition of date +/- Quantity arithmetic operation support.

### CODE REVIEW

**Comment by grahamegrieve** [comment]
Before I can accept this PR, please make a PR for the tests against the master FHIRPath tests here: https://github.com/FHIR/fhir-test-cases/blob/master/r5/fhirpath/tests-fhir-r5.xml and then ask the FHIRPath community to sign off on the proposed tests at https://chat.fhir.org/#narrow/stream/179266-fhirpath

**Comment by grahamegrieve** [comment]
I won't be accepting this PR. Thanks for the submission, and I worked from your code, but ended up submitting something slightly different for date addition/subtraction after reconciling all the tests in R5.

Please explain the issue with error location.

**Comment by keithboone** [comment]
Runtime errors don’t report where in the code the failure is occurring.  It’s a bit of a challenge when you have a long expression to debug which part is failing.

So I wrapped the inner code in execute() in a try catch block, and if PathEngineException is caught, store the sub-expression and location if one has not already been set in the caught PathEngineException exception, and rethrow it.  I added methods to enable storage and retrieval of the location information from the exception.

                Keith



Keith Boone, Enterprise Architect
kboone@ainq.com | (617) 640-7007

AUDACIOUS INQUIRY
Bold Solutions for Connected Healthcare®
ainq.com<https://ainq.com/>|Twitter<https://twitter.com/a_inq>|YouTube<https://www.youtube.com/channel/UCF-wA3wcjce8YniZhxy1O4Q>|Facebook<https://www.facebook.com/AudaciousInquiry/>| LinkedIn<https://www.linkedin.com/company/audacious-inquiry-llc>

**Comment by grahamegrieve** [comment]
ok. fixed in the main. thx

**Pull request closed without merging**
