### PR TITLE
Enable bulk -snapshot and -convert on multiple/wildcard -source

### PR DESCRIPTION
**Pull request by david-simons**
as per Zulip chat: <https://chat.fhir.org/#narrow/stream/179166-implementers/topic/validator.20generate.20snapshots.20multiple.20source.20into.20bundle/near/302886236>

### CODE REVIEW

**Comment by david-simons** [comment]
- builds successfully (`org.hl7.fhir.validation.cli-5.6.70-SNAPSHOT.jar` currently)
- the two fixes on http to https are because of `501 HTTPS Required. Use https://repo.maven.apache.org/maven2/. More information at https://links.sonatype.com/central/501-https-required` when building via `mvn -DfhirTxcacheRebuild -DskipTests clean install`
- Simplified-up terminal output:

```
PS vitalSign-v1> java -jar validator_cli.jar *.structuredefinition.xml -version 4.0.1 -jurisdiction uv -snapshot -output snapshot.json
FHIR Validation tool Version 5.6.70-SNAPSHOT (Git# 17d265b9d81d). Built 2022-10-07T22:31:09.77+02:00 (25 mins old)
  Java:   17 from C:\Program Files\jdk-17 on amd64 (64bit). 2018MB available

  Paths:  Current = vitalSign-v1, Package Cache = .fhir\packages     
  Params: BloodPressureVitalSign.structuredefinition.xml BMIVitalSign.structuredefinition.xml BodyTemperatureVitalSign.structuredefinition.xml HeadCircumferenceVitalSign.structuredefinition.xml HeartRateVitalSign.structuredefinition.xml HeightVitalSign.structuredefinition.xml OxygenSaturationVitalSign.structuredefinition.xml RespiratoryRateVitalSign.structuredefinition.xml VitalSign.structuredefinition.xml WeightVitalSign.structuredefinition.xml -version 4.0.1 -jurisdiction uv -snapshot -output snapshot.json
  Jurisdiction: No Jurisdiction
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1 - 4575 resources (00:06.628)
  Load hl7.terminology#4.0.0 - 4164 resources (00:02.135)
  Load R5 Extensions - 85 resources (00:11.339)
  Terminology server http://tx.fhir.org - Version 2.0.14 (00:01.275)
  Get set...  go (00:00.050)
 ...generated snapshot [0] successfully
 ...generated snapshot [1] successfully
 ...generated snapshot [2] successfully
 ...generated snapshot [3] successfully
 ...generated snapshot [4] successfully
 ...generated snapshot [5] successfully
 ...generated snapshot [6] successfully
 ...generated snapshot [7] successfully
 ...generated snapshot [8] successfully
 ...generated snapshot [9] successfully
Done. Times: Loading: 00:21.812. Max Memory = 1Gb
PS vitalSign-v1> 
```
Resulting files:
image

**Comment by david-simons** [comment]
@grahamegrieve requesting this to become part of the HL7 Validator release - it brings our nightly build down from many hours down to a few minutes - by being able to use wildcards on -source for the -convert and for the -snapshot operations.

**Review by dotasek — CHANGES_REQUESTED** [review]
It seems to me that the output files generated here will have names decoupled from their sources.

In your example, BloodPressureVitalSign.structuredefinition.xml could be any one of [x].snapshot.json. which may work when loading the whole directory, but could make debugging a pain.

What I would suggest is adding another option, perhaps `-outputSuffix` that gets used in the place of `-output` in the case where there is more than one source.

So, for example using `-outputSuffix .snapshot.xml`, you would get `BloodPressureVitalSign.structuredefinition.xml.snapshot.xml`.

Does this seem reasonable?

**Review by dotasek — CHANGES_REQUESTED** [review]
Regarding your previous comments, I can make some adjustments to your PR myself to make it utilize a `-outputSuffix` argument. I appreciate wanting to minimize code changes, but I'd like to avoid situations where parameters have different meanings depending on context.

I like the idea of explicitly printing out the mapping from input to output; that should help users with debugging if anything goes wrong.

**Comment by dotasek** [comment]
@david-simons one more consideration, which I'll have to check myself: what happens with a mixture of input files?

```
BloodPressureVitalSign.structuredefinition.xml
BMIVitalSign.structuredefinition.json
...
```

I will have to check the logic, but I believe the output will match formats, meaning the suffix will have to change for each file:

```
BloodPressureVitalSign.structuredefinition.output.xml
BMIVitalSign.structuredefinition.output.json
...
```

The argument would simply be `-outputSuffix output` in this case.

**Comment by david-simons** [comment]
> @david-simons one more consideration, which I'll have to check myself: what happens with a mixture of input files?

I checked, and the conversion is actually determined by the single -output parameter, not by the mixed input! So it is predicteable.

Example: a combination of xml+json input will be converted to .json, when -convert -output convert.json
(determined by the type out the -output parameter, nicely)

```
vitalSign-v1> java -jar C:\Users\nlv09099\Source\Repos\org.hl7.fhir.core-fork\org.hl7.fhir.validation.cli\target\org.hl7.fhir.validation.cli-5.6.71-SNAPSHOT.jar .\BloodPressureVitalSign.structuredefinition.xml .\BloodPressureVitalSign.structuredefinition.json -version 4.0.1 -jurisdiction uv -convert -output convert.json       
FHIR Validation tool Version 5.6.71-SNAPSHOT (Git# dd65b1a40fa6). Built 2022-10-12T10:26:39.911+02:00 (46 hours old)
  Java:   17 from C:\Program Files\jdk-17 on amd64 (64bit). 2018MB available

Loading
<cut>
  Get set...  go (00:00.048)
 ...convert [0] (.\BloodPressureVitalSign.structuredefinition.xml to .\BloodPressureVitalSign.structuredefinition.xml.convert.json)
 ...convert [1] (.\BloodPressureVitalSign.structuredefinition.json to .\BloodPressureVitalSign.structuredefinition.json.convert.json)
Done. Times: Loading: 00:20.986. Max Memory = 1Gb
```

**Comment by david-simons** [comment]
Thanks - I merged in your additional commit (
`Tests and add new parameter`), @dotasek, and @cdejonge and I will give these a try in our pipeline asap

**Comment by david-simons** [comment]
Have a look at my additional commits on this branch @dotasek - adding logic for `-output XOR -outputSuffix` - tested also.
This will allow us to use the -outputSuffix also with a single -source file; next to of course using -output with a single -source file.
The choice is determined by using either -output XOR -outputSuffix.

help.txt to be updated still

**Pull request merged**
