### PR TITLE
Adds maven plugin to display issues related to android compatibility.

### PR DESCRIPTION
**Pull request by vitorpamplona**
Adds the Animal Sniffer plugin to visualize errors related to Android, similar to what we did on https://github.com/hapifhir/hapi-fhir/pull/4070. 

The plugin runs on `mvn test` without failing the build. 

To run the analysis alone, do: `./mvnw animal-sniffer:check`
 
Current Issues: 
1. Current [`DigitalSignatures`](https://github.com/hapifhir/org.hl7.fhir.core/blob/6bd8dd257e8574d51b64cdc77a9e22a93dcf1bbb/org.hl7.fhir.r4/src/main/java/org/hl7/fhir/r4/utils/DigitalSignatures.java#L88) classes contains links to crypto tools not available on Android. This looks like prototype code. I am not sure these are being used anywhere. Maybe just delete? 
2. [XmlLocationAnnotator](https://github.com/hapifhir/org.hl7.fhir.core/blob/8706b3c4a4715ba4d8e53bd5a0b384e02fd2db54/org.hl7.fhir.r4b/src/main/java/org/hl7/fhir/r4b/utils/formats/XmlLocationAnnotator.java#L64) classes use Event Listening (`org.w3c.dom.events.MutationEvent`, `org.w3c.dom.events.EventTarget`) which is not available on Android
3. [HierarchicalTableGenerator](https://github.com/hapifhir/org.hl7.fhir.core/blob/42969db5bcb6b19321d65c05ff9c9ab44c8fb32d/org.hl7.fhir.utilities/src/main/java/org/hl7/fhir/utilities/xhtml/HierarchicalTableGenerator.java#L88) in utilities makes reference of several `AWT` components that are not available on Android. 
4. [FilesystemPackageCacheManager](https://github.com/hapifhir/org.hl7.fhir.core/blob/8b7890bea2e34f9c29e31e1a0a6e915c0b7ac6e2/org.hl7.fhir.utilities/src/main/java/org/hl7/fhir/utilities/npm/FilesystemPackageCacheManager.java#L429) makes use of `java.sql.Timestamp`, which is not available on Android. 

This does not catch or solve: https://github.com/hapifhir/org.hl7.fhir.core/issues/1046

### CODE REVIEW

**Review by dotasek — CHANGES_REQUESTED** [review]
Why specifically API level 26 when it doesn't support Java 11, which is our compilation target? (see earlier comment in PR)

**Comment by dotasek** [comment]
@vitorpamplona OK. Approved. Could you commit to this branch again with a merge from master? I just want to verify that all the checks run without error after the last updates to master.

**Comment by vitorpamplona** [comment]
Perfect. I just merged master into it. I hope it works!

**Comment by dotasek** [comment]
@vitorpamplona merged. Thanks for your patience!

**Comment by JPercival** [comment]
@dotasek - Just to help clarify the Java 11 aspect: There are two aspects Java 11, new language features (like 'var') and new platform APIs (like Optional.isPresent). Android _does_ support the Java 11 language features via a process called desugaring. It's the platform APIs that are only partially implemented. The Java compiler doesn't have a way to set 'source=11', ' target=11', 'release=8.5' That's why animal-sniffer is used. You leave the compiler settings for 11, and animal-sniffer then detects usages of APIs not implemented on Android.

**Pull request merged**
