### PR TITLE
Add SubscriptionTopic and SubscriptionStatus conversions for R4B <-> R5

### PR DESCRIPTION
**Pull request by dotasek**
Adds feature for #1212

Note that this conversion only covers the minimal examples provided by the R5 spec, and by @fil512. 

This conversion will also be inherently lossy where fields are not 1-to-1 matches (as in SubscriptionSearchModifier).

### CODE REVIEW

**Review by grahamegrieve — COMMENTED** [review]
this:

if (src.hasEventsSinceSubscriptionStart()) {
       org.hl7.fhir.r4b.model.StringType value = new org.hl7.fhir.r4b.model.StringType();
       value.setValue(src.getEventsSinceSubscriptionStartElement().getValueAsString());
       tgt.setEventsSinceSubscriptionStartElement(value);
     }

why does isn't follow the normal pattern? This will drop extensions, and so it will eventually need to be redone. This PR should be redone using the normal patterns (and there's a spelling mistake - covert)

**Comment by dotasek** [comment]
> why does isn't follow the normal pattern? 

What is the normal pattern for this? 

EventsSinceSubscription is not an extension. All that appears to differ is the type (String in one, integer64 in the other). Is there a place in the existing code following the pattern you'd like?

Is this the only place in this conversion that this is incorrect?

**Comment by grahamegrieve** [comment]
oh? that's unfortunate that's the first I looked at. We do it like this: org.hl7.fhir.convertors.conv40_50.datatypes40_50.primitive40_50.String40_50.convertStringToMarkdown(StringType) - pick one of the two types, and add a conversion there. In this case, I'd add a convertStringToInteger to String since the type Integer64 doesn't exist at this time

**Comment by dotasek** [comment]
One @grahamegrieve's recommendation, I'll be expanding this conversion to cover the full resources, not just what is required of the examples.

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
