### PR TITLE
#1583 do not serialize choice group

### PR DESCRIPTION
**Pull request by oliveregger**
see issue https://github.com/hapifhir/org.hl7.fhir.core/issues/1583, this PR don't serialize the elements which are a choice group

### CODE REVIEW

**Comment by grahamegrieve** [comment]
@oliveregger apologies for not getting to this one sooner. Do we have a test case for this?

**Comment by grahamegrieve** [comment]
@oliveregger ping?

**Comment by oliveregger** [comment]
1. https://github.com/FHIR/fhir-test-cases/pull/181 needs to be updated that we have a choice group
2. added a testcase in this PR that it is verifed that the serialization into cda does not contain an <item> element anymore.

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
