### PR TITLE
Update fhir-path-tests.xml

### PR DESCRIPTION
**Pull request by jkiddo**
Added consecutive FHIRpath tests

### CODE REVIEW

**Comment by dotasek** [comment]
Is this code dead?

Where are these tests actually executed? The only reference I can find to them is in testcases.ini in the FHIR spec code (https://github.com/HL7/fhir/blob/master/tests/testcases.ini), which in turn seems to be referenced nowhere. 

The Git blame in these is quite old, some of it dating back to 2017, and there are commits around it with wording like "[Remove IG publisher (it's gone to Maven)](https://github.com/HL7/fhir/commit/56ceb0df08dd72381a4f98f1ea4ac5ea6d139a8b)"

**Comment by grahamegrieve** [comment]
yes - these changes should be made to https://github.com/FHIR/fhir-test-cases/blob/master/r4/patch/fhir-path-tests.xml

**Comment by jkiddo** [comment]
Oversight from my side - I will provide a new PR. Why not delete the old file?

**Comment by grahamegrieve** [comment]
I will

**Comment by jkiddo** [comment]
@grahamegrieve -> https://github.com/FHIR/fhir-test-cases/pull/133

**Pull request closed without merging**
