### PR TITLE
add readme for convertors

### PR DESCRIPTION
**Pull request by ItayGoren**

### CODE REVIEW

**Comment by markiantorno** [comment]
Hey, this is great, but it might be better to put it in the github project wiki section instead. Realistically, we need a lot more documentation for the various modules, and i don't think it would be great practice to have separate README files in the various sections. Linking to the wiki from the main README would probably be the best way to go about this.

**Comment by ItayGoren** [comment]
I agree we need more documentation but it's a start :) How can i get edit permissions for the wiki? Never worked with it before.

**Comment by markiantorno** [comment]
I've pasted what you have submitted into a wiki page for the convertors:
https://github.com/hapifhir/org.hl7.fhir.core/wiki/Convertors

Thanks for taking the time to write this up. As we get more documentation, we can look at a better landing page for the wiki, and better organization. If you have any suggestions, please let me know!

**Comment by markiantorno** [comment]
Closing, as the documentation was added to the wiki.

**Pull request closed without merging**
