### PR TITLE
Implement private NPM server

### PR DESCRIPTION
**Pull request by dotasek**
Implements access to private NPM servers.

Usage:

The `.fhir/fhir-settings.json` will contain a packageManagement element with configured servers:

```
"packageManagement" : {
    "ignoreDefaultServers" : true,
     "servers": [
      {
        "url" : "http://0.0.0.0:4873",
        "serverType" : "npm",
        "authenticationType" : "BASIC",
        "username" : "alfred",
        "password" : "numan"
      }
    ]
}
``` 

When a package is requested, these servers are checked before those provided by PackageServer.defaultServers(). If ignoreDefaultServers is set to true, the servers provided by PackageServer.defaultServers() will not be used.

Two types of servers are supported: FHIR/default which behaves in the same way as simplifier.net package servers, and NPM, which behaves according to the following API:  https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md

Basic authentication is implemented, if the authenticationType is set to `BASIC`.

### CODE REVIEW

**Comment by dotasek** [comment]
@DarthGizka @grahamegrieve : the PR description and the logic for which servers to check for packages have been changed as per @grahamegrieve 's input. The default servers can now be set to be ignored.

**Comment by dotasek** [comment]
@grahamegrieve @DarthGizka one more change: token authorization is now supported. Let me know if this is OK to merge.

**Comment by dotasek** [comment]
Nope, never mind, found a bug. Fixing now.

**Comment by dotasek** [comment]
Fixed. Ready for review.

**Review by grahamegrieve — APPROVED** [review]
looks good, but can we document it here: /documentation.md

**Pull request merged**
