### PR TITLE
date adaption for dateOp #1655

### PR DESCRIPTION
**Pull request by oliveregger**
- missed dateTime handling
- needed to separate dateTime and date handling due to failing FHIRPath tests
- see update testcase for variable handling with StructureMap and FHIRPath in https://github.com/FHIR/fhir-test-cases/pull/178

### CODE REVIEW

**Review by grahamegrieve — APPROVED** [review]
ok

**Comment by grahamegrieve** [comment]
for some reason, this PR was not processed with the other, so I fixed it differently. can you resolve the conflicts please

**Comment by oliveregger** [comment]
PR is updated, conflict resolved

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
