### PR TITLE
Pw fix line validation with pattern

### LINKED ISSUE #423: Address.line with pattern always failing to validate
When using a  pattern on Address, the validation of line always fails. This is caused by the validator comparing length of line vs fixedline. 
With pattern, line.length() can be >= as fixedline.length()

### PR DESCRIPTION
**Pull request by patrick-werner**
this fixes the Address Validation with pattern. Address line always failed to validate on pattern as the implementation was limited to fixedValue validation.

fixes #423

### CODE REVIEW

**Review by markiantorno — APPROVED** [review]

**Review by markiantorno — CHANGES_REQUESTED** [review]
Add a line to the RELEASE_NOTES file describing what the change is please.

**Comment by grahamegrieve** [comment]
There isn't a matching test case in the validation test cases for this change. Changes to the validator always need a test case please

**Comment by patrick-werner** [comment]
ok will dig into the test-case stuff and add a test-case.

**Comment by grahamegrieve** [comment]
hasn't this work been done now?

**Comment by patrick-werner** [comment]
still an issue, added TestCase:
https://github.com/FHIR/fhir-test-cases/pull/91

**Comment by grahamegrieve** [comment]
Well, this PR has merge conflicts, and I didn't understand the changes. so I made this change through https://github.com/hapifhir/org.hl7.fhir.core/pull/525

**Pull request closed without merging**
