### PR TITLE
Terminology client headers

### PR DESCRIPTION
**Pull request by markiantorno**
@grahamegrieve please review this. If you're okay with how it is setup, I'm just going to copy it over to dstu2-r4 as well. Right now this is only for r5.

### CODE REVIEW

**Review by grahamegrieve — COMMENTED** [review]
why is there multiple identical implementations of ClientHeaders?

**Review by grahamegrieve — COMMENTED** [review]
And why are the headers only actually implemented for R5?

**Comment by markiantorno** [comment]
> And why are the headers only actually implemented for R5?

I am unsure why the changes didn't get added (I must have run git add from a sub directory and not from the convertors project), but they are pushed up now

**Comment by markiantorno** [comment]
> why is there multiple identical implementations of ClientHeaders?

I followed the existing convention where the network code, while similar between versions, was just copied from version to version. I can pull it out and put it in utilities in another PR if you'd like, but I'd like to get this one in as it is now, if possible.

**Review by grahamegrieve — APPROVED** [review]
ok

**Comment by grahamegrieve** [comment]
I think it would be good to rationalise the code so code that only needs to be in one place is only in one place

**Comment by markiantorno** [comment]
> I think it would be good to rationalise the code so code that only needs to be in one place is only in one place

Oh god yes. I think 95% of the networking code should be in it's own package and just return IBaseResources.

**Pull request merged**
