### PR TITLE
#133: Escape just embedded HTML tags, not autolinks in Markdown

### PR DESCRIPTION
**Pull request by pieter-edelman-nictiz**

### CODE REVIEW

**Comment by dotasek** [comment]
Shouldn't the preProcess method now allow `<http://link.com>` style links? The code is changed there, but the tests in MarkdownPreprocessorTesting don't have a case for this.

**Comment by pieter-edelman-nictiz** [comment]
Ah, forgot to link this back to issue https://github.com/hapifhir/org.hl7.fhir.validator-wrapper/issues/133. Sorry, I mixed up the repo's.

**Comment by dotasek** [comment]
I'll take a look at the fix soon.

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
