### PR TITLE
Corrected ObligationsRenderer to handle multiple actors and multiple …

### PR DESCRIPTION
**Pull request by lmckenzi**
…codes.  Also got obligations with elements to render properly (which means knowing whether you're on a table page or definitions page, what tab you're on, and whether the element for the obligation is in-scope for that tab (so you know whether to hyperlink or not).  Had to make links on the tables point to definitions because table anchors are not unique.

### CODE REVIEW

**Review by grahamegrieve — COMMENTED** [review]
why the changes to the old versions? Does this pass the test cases?

**Comment by lmckenzi** [comment]
IntelliJ said the code wasn't used anywhere, and it seemed better to remove the modules than update them.  Why would the test cases use them if nothing else does?

**Comment by grahamegrieve** [comment]
> IntelliJ said the code wasn't used anywhere, and it seemed better to remove the modules than update them.

They're public, so you don't know whether they're being used. How are they relevant?

> Why would the test cases use them if nothing else does?

The test cases question was about your actual code

**Comment by lmckenzi** [comment]
See https://github.com/FHIR/fhir-test-cases/pull/173

**Comment by grahamegrieve** [comment]
I still can't accept this until the removed code is restored

**Review by grahamegrieve — APPROVED** [review]
ok. will fix up afterwards

**Pull request merged**
