### PR TITLE
Handle extra profiles on resources in an IG

### PR DESCRIPTION
**Pull request by lmckenzi**

### CODE REVIEW

**Review by grahamegrieve — APPROVED** [review]
ok

**Comment by grahamegrieve** [comment]
Not ok. Given that this didn't even compile when submitted, we need to see passing test cases before accepting this

**Review by grahamegrieve — COMMENTED** [review]
we going to get a test case for this?

**Comment by lmckenzi** [comment]
Test case added.  Apologies for the compile issues - dunno why IntelliJ wasn't picking them up.

**Review by grahamegrieve — APPROVED** [review]
ok

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
