### PR TITLE
#1264 add R5 TestPlan conversion classes to R3, R4 and R4B

### PR DESCRIPTION
**Pull request by rettema**
R5 TestPlan conversion classes added for R3, R4 and R4B
R5 TestPlan renderer class added
R5 Requirements renderer class updated with minor enhancements

### CODE REVIEW

**Review by grahamegrieve — COMMENTED** [review]
What's with the % coverage changes in the Requirements renderer - how does that work?

**Comment by rettema** [comment]
Trying to show a meaningful connection between the statements and how many of them have corresponding artifacts that "satisfy" (provide coverage of) those statements. I realize that it's extra calculated information not actually stored as part of the Requirements resource instance and can remove it if you feel it's not appropriate for the renderer.

**Comment by grahamegrieve** [comment]
I think we should remove it because it's misleading - most requirements will be satisfied elsewhere. It's an unusual case for the requirement to post-documentation (which is when you fill out the satisfiedBy element)

**Comment by rettema** [comment]
Understood. Anything else before I commit that change?

**Pull request merged**
