### PR TITLE
#830,#831. support for JSON only Terminology server automatically and make timeout longer for slow terminology server 

### PR DESCRIPTION
**Pull request by kazuhiko-ohe**
1) for #830
added new switchResourceFormat() from line#164  and calling it from within getCapabilitiesStatementQuick() at line#186-187  of org.hl7.fhir.r5.utils.client.FHIRToolingClient

By this addition, json only terminology server will also work. A Terminology server (eg.  https://tx.jpfhir.jp/ ) that supports only JSON format was tested and worked by this addition.  
2) Since external terminology server may need long time out (for example, in the case of a terminology server that dynamically generates a terminology capabilityStatement from its own CodeSystem and ValueSet Resource.), add the sentence TIMEOUT_NORMAL_EXTERNAL_TX = TIMEOUT_OPERATION_EXPAND , and used at line#143 calling  (TerminologyCapabilities) client.issueGetResourceRequest(...

### CODE REVIEW

**Comment by dotasek** [comment]
The failing tests appear to be impacting all PRs, not just this one. I will try to diagnose what's wrong.

**Comment by grahamegrieve** [comment]
I don't understand the question about timeouts. Was the server overloaded at the time?

**Comment by kazuhiko-ohe** [comment]
>

**Comment by kazuhiko-ohe** [comment]
@dotasek  Thank you for your advice. 
> * There are ~ no new test case covering the new code.
 I understand.  I'll try. 

> * The catch you added will catch any exception; I believe this needs to catch the exception specific to XML processing, or else our exception reporting will lose the first round of exceptions from any server.
> * Related to point 2, I'd rather have very specific decisions made when switching the preferred resource format. I would suggest something like this, expressed as code
Yes, I also thought that this proposal needed a more specific approach. I'll try to make better approach.
We have not yet found the location of the process that is detecting that the request response is not xml nor allowed. Servers that only process JSON are expected to return a response code of 406 or 421 when the client requests XML, so  I  could  check this response code and try again in JSON. The FHIR specification doesn't seem to specify a procedure to negotiate XML or JSON when getting the first capabilityStatement. The capabilityStatement has a format element, but unfortunately it cannot be used unless the capabilityStatement in the resource format that can be processed is responded.

**Comment by kazuhiko-ohe** [comment]
@dotasek 
I could not why so many failings occured only by changing TIMEOUT parameter.

**Comment by dotasek** [comment]
@kazuhiko-ohe The reported test failures are actually unrelated to your code; I edited my earlier message, and left another indicating this. Apologies if you still spent time investigating them.

Grahame and I are attempting to fix these ourselves; once they are repaired, I will re-run the pipelines on this PR so at least those tests pass again.

**Comment by dotasek** [comment]
@grahamegrieve ignore my initial timing question; this PR changed the timeout for server access, and the initial failing tests were coincidentally reporting test failures on timingTiming elements in JSON. They are actually unrelated.

**Comment by grahamegrieve** [comment]
I don't like the name TIMEOUT_NORMAL_EXTERNAL_TX - what does it mean, that constant?

**Comment by dotasek** [comment]
@kazuhiko-ohe Please check #838

The solution proposed there includes tests, covers and SHOULD report all failures and attempt all available formats.

I am not changing the timeout. As per the tests, I'd expect a server to fail fast on such a basic query.

**Pull request closed without merging**
