### PR TITLE
Example scenario rendering

### PR DESCRIPTION
**Pull request by lmckenzi**
Add ability to render ExampleScenarios, including diagrams

### CODE REVIEW

**Comment by grahamegrieve** [comment]
This POM change brings GPL code into the library, and we can't accept it at all.

**Comment by grahamegrieve** [comment]
looking at the code, we really think that you should use a StringBuilder at line 117 of the ExampleScenarioRenderer.java

**Comment by lmckenzi** [comment]
> looking at the code, we really think that you should use a StringBuilder at line 117 of the ExampleScenarioRenderer.java

Updated to use StringBuilder as suggested.

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
