### PR TITLE
Pw/translations de

### PR DESCRIPTION
**Pull request by patrick-werner**
added missing german translations

### CODE REVIEW

**Comment by patrick-werner** [comment]
#closes #990

**Comment by dotasek** [comment]
This is actually quite difficult to review, as many keys and values have changed.

To make this easier, I am working on developing some unit tests to do several things:

1. To report how many message definitions from I18nConstants are covered in each language, so we can track whether coverage has increased/decreased in a particular commit.
2. To confirm that plural phrases are completely constructed in each language.

Please be patient as I build this test; I will use this PR to help refine it.

**Comment by dotasek** [comment]
I added a test that reports any missing property keys, and also verifies that all plural phrases are present.

There were a few fixes that needed to be done in other languages, but the original updates in this PR all seem valid.

**Comment by patrick-werner** [comment]
> I added a test that reports any missing property keys, and also verifies that all plural phrases are present.
> 
> There were a few fixes that needed to be done in other languages, but the original updates in this PR all seem valid.

thanks for the quick review, adding automated translation coverage checks seems to be great.
I noticed that some keys are not used anymore, or some phrases only exist in e.g. spanish. This might be another great area to automatically test.

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
