### PR TITLE
Fixed issues with ExampleScenario conversion.  resourceType was getti…

### PR DESCRIPTION
**Pull request by lmckenzi**
…ng stripped, as was operation.number.

### CODE REVIEW

**Review by grahamegrieve — COMMENTED** [review]
why are the changes to convertExampleScenarioProcessStepOperationComponent only made in one direction?

**Comment by lmckenzi** [comment]
It's asymmetrical.  One way the change is on StepOperation, the other way it's on Step.

**Comment by dotasek** [comment]
@lmckenzi Could we get a simple test going so this at least doesn't regress?

**Comment by lmckenzi** [comment]
@dotasek where do conversion test cases live?  I don't see anything relevant in the 'conversion' folder, or anywhere else I can think to look...

**Comment by dotasek** [comment]
Since these are native to Java, they live in the core code. This one, I believe would live in org.hl7.fhir.convertors/src/test/java/org/hl7/fhir/convertors/conv40_50

There will be other test cases there that you can follow, and you can check the [README](https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.convertors/README.md) for a rundown on common patterns.

I maintain that, so feel free to reach out here or on Zulip if anything is unclear.

**Comment by lmckenzi** [comment]
Ok, that uncovered a whole bunch of other issues.  Conversion process significantly enhanced and TestCase committed.

**Comment by dotasek** [comment]
The conversion test looks appropriate.

However, if I try to validate that test resource, I get a lot of errors:

```log
> java -jar validator_cli.jar -allow-example-urls true resource.xml 

FHIR Validation tool Version 6.0.21 (Git# 45ae02cf1d56). Built 2023-07-07T12:36:50.156Z (7 days old)
  Java:   17.0.5 from /opt/homebrew/Cellar/openjdk@17/17.0.5/libexec/openjdk.jdk/Contents/Home on aarch64 (64bit). 4096MB available
  Paths:  Current = /Users/david.otasek/IN/2023-07-14-lloyd-conversion-pr, Package Cache = /Users/david.otasek/.fhir/packages
  Params: -allow-example-urls true resource.xml
Scanning for versions (no -version parameter):
  No Version Info found: Using Default version R5
  Locale: Canada/CA
  Jurisdiction: Canada
Loading
  Load FHIR v5.0.0 from hl7.fhir.r5.core#5.0.0  Load hl7.terminology.r5#5.0.0 - 4174 resources (00:18.208)
  Load hl7.fhir.uv.extensions#1.0.0 - 1328 resources (00:00.040)
 - 8454 resources (00:00.000)
  Load hl7.terminology#5.1.0 - 4180 resources (00:01.416)
  Terminology server http://tx.fhir.org - Version 2.1.0 (00:00.537)
  Package Summary: [hl7.fhir.r5.core#5.0.0, hl7.fhir.xver-extensions#0.0.12, hl7.terminology.r5#5.0.0, hl7.fhir.uv.extensions#1.0.0, hl7.terminology#5.1.0]
  Get set...  go (00:04.022)
Validating
  Validate resource.xml
Validate ExampleScenario against http://hl7.org/fhir/StructureDefinition/ExampleScenario|5.0.0..........20..........40..........60..........80.........|
 00:00.947
Done. Times: Loading: 00:24.796, validation: 00:00.948. Memory = 582Mb

*FAILURE*: 5 errors, 3 warnings, 0 notes
  Error @ ExampleScenario.instance[0] (line 86, col12): Rule exs-2: 'instance.content is only allowed if there are no instance.versions' Failed
  Error @ ExampleScenario.process[0].step[0].alternative[0].step[0].process.step[1].operation.request (line 228, col26): Rule exs-14: 'InstanceReference must be a key of an instance defined in the ExampleScenario' Failed
  Error @ ExampleScenario.process[0].step[0].alternative[0].step[0].process.step[1].operation.response (line 231, col27): Rule exs-14: 'InstanceReference must be a key of an instance defined in the ExampleScenario' Failed
  Error @ ExampleScenario.process[0].step[1].operation.request (line 251, col14): Rule exs-14: 'InstanceReference must be a key of an instance defined in the ExampleScenario' Failed
  Error @ ExampleScenario.process[0].step[1].operation.response (line 254, col15): Rule exs-14: 'InstanceReference must be a key of an instance defined in the ExampleScenario' Failed
  Warning @ ExampleScenario.jurisdiction[0] (line 59, col17): No code provided, and a code should be provided from the value set 'Jurisdiction ValueSet' (http://hl7.org/fhir/ValueSet/jurisdiction|5.0.0)
  Warning @ ExampleScenario.jurisdiction[1] (line 62, col17): No code provided, and a code should be provided from the value set 'Jurisdiction ValueSet' (http://hl7.org/fhir/ValueSet/jurisdiction|5.0.0)
  Warning @ ExampleScenario.instance[1] (line 128, col12): Rule exs-20: 'Instance should be referenced in at least one location' Failed
```

**Comment by lmckenzi** [comment]
Addressed

**Comment by dotasek** [comment]
Looks good to me!

**Comment by grahamegrieve** [comment]
Abandoned this - too many conflicts. Remade the changes in another PR

**Pull request closed without merging**
