### PR TITLE
Test showing that extensions are not carried over

### PR DESCRIPTION
**Pull request by jkiddo**

### CODE REVIEW

**Comment by grahamegrieve** [comment]
carumba, this one's a pig to deal with. I'm not sure it's a bug, in fact, it's a long standing design decision.

**Comment by jkiddo** [comment]
Ehhm.... what?
This happens for enumeration elements only. Do it with eg. name and the extensions are carried over just fine.

**Comment by grahamegrieve** [comment]
I think, from looking at the code, that it happens with primitive types

**Comment by jkiddo** [comment]
Nope - works fine for e.g. booleans. Its a problem for all the castTo* called in the setProperty which do a `hasPrimitiveValue()` - and that seems ... well ... a bit inconsistent

**Comment by grahamegrieve** [comment]
see https://chat.fhir.org/#narrow/stream/179167-hapi/topic/SetProperty.20.26.20primitives

**Comment by grahamegrieve** [comment]
why close it? Might as well keep the test

**Pull request closed without merging**
